In [1]:
# Import modules
import numpy as np

### Define parameters

In [15]:
# Define parameters - Haverkamp et al.

# Hydraulic conductivity
K_s = 34 # Saturated hydraulic conductivity, cm/h
A = 1.175E6 # -
beta_K = 4.74 # - d

# Water saturation - pressure head relation
theta_s = 0.287 # Saturation: the value of theta for which h is zero
theta_r = 0.075
alpha = 1.611e6
beta_theta = 3.96

Create mesh


#### Analytical expressions with parameters fitted from soil-water experimental data
This functions are defined from Haverkamp (1977)

In [16]:
def theta_fun(h, alpha=alpha, theta_s = theta_s, theta_r = theta_r, 
              beta_theta = beta_theta):
    return (alpha * (theta_s-theta_r) / (alpha + np.abs(h)**beta_theta) +
            theta_r)

def K(h, K_s=K_s, A=A,  beta_K=beta_K):
    return K_s * A /(A + np.abs(h)**beta_K)
    

Boundary conditions

Soil water diffusivity

$$ D(\theta) = \frac{K(\theta)}{C(\theta)}$$

Specific water capacity

$$ C(\theta) = \frac{d \theta}{d h} $$

Noting that this derivative implies that there is a unique relation between the volumetric water content, $\theta$, and the soil water pressure relative to the atmosfere in cm of water.

#### Constant flux condition at the soil surface

$$ \frac{\partial \theta}{\partial z}|_{z=0} = \frac{K-q_0}{D} $$

After multiplying the matrices, we need to have a vector with the time derivatives of the dependent variable, in this case, $h$ o $\psi$ depending on the nomenclature.

In [ ]:
n_z = 100 # Number of nodes

# Initial conditions
psi_0 = np.
# Initial and boundary conditions

Build the system of differential equations

- After multiplying the matrices, we need to have a vector with the time derivatives of the dependent variable, in this case, $h$ o $\psi$ depending on the nomenclature.
- In each time-step, the matrices need to be updated.

In [18]:
import numpy as np

# Define a square matrix
matrix = np.array([[4, 7],
                   [2, 6]])

# Compute the inverse
try:
    inverse_matrix = np.linalg.inv(matrix)
    print("Inverse of the matrix:")
    print(inverse_matrix)
except np.linalg.LinAlgError:
    print("Matrix is singular and cannot be inverted.")


Inverse of the matrix:
[[ 0.6 -0.7]
 [-0.2  0.4]]


In [19]:
matrix

array([[4, 7],
       [2, 6]])

In [21]:
np.dot(matrix,inverse_matrix)

array([[ 1.00000000e+00, -1.11022302e-16],
       [-1.11022302e-16,  1.00000000e+00]])